apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    releaseName: postgres
    namespace: monitoring
    version: 15.2.5
    valuesFile: values.yaml
