apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-config
data:
  REDIS_HOST: redis-master.monitoring.svc.cluster.local
  POSTGRES_HOST: postgres-postgresql.monitoring.svc.cluster.local
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
