resources:
  - https://charts.bitnami.com/bitnami/redis

helmCharts:
  - name: redis
    releaseName: redis
    version: 19.1.2
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
